"""Idempotent template copying for BrainStormer."""

import shutil
from pathlib import Path
from datetime import datetime


def get_brainstormer_root() -> Path:
    """Find the BrainStormer installation root (where SKILL.md lives)."""
    # Walk up from this file to find the BrainStormer root
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "SKILL.md").exists() and (parent / "manifest.json").exists():
            return parent
    # Fallback: assume standard layout
    return Path(__file__).resolve().parent.parent.parent


def copy_if_missing(src: Path, dest: Path, replacements: dict = None) -> str:
    """Copy a file only if the destination doesn't exist.

    Returns: 'created', 'skipped', or 'error'
    """
    if dest.exists():
        return "skipped"

    try:
        dest.parent.mkdir(parents=True, exist_ok=True)

        if replacements:
            content = src.read_text(encoding="utf-8")
            for key, value in replacements.items():
                content = content.replace(key, value)
            dest.write_text(content, encoding="utf-8")
        else:
            shutil.copy2(src, dest)

        return "created"
    except Exception as e:
        return f"error: {e}"


def scaffold_kernel(project_root: Path, project_name: str) -> dict:
    """Scaffold the 10 Kernel template files.

    Returns dict of {filename: status}.
    """
    bs_root = get_brainstormer_root()
    templates_dir = bs_root / "kernel" / "templates"
    results = {}

    replacements = {
        "[PROJECT_NAME]": project_name,
        "[project_name]": project_name.lower().replace(" ", "-"),
        "[DATE]": datetime.now().strftime("%Y-%m-%d"),
    }

    template_files = [
        "CLAUDE.md", "SPEC.md", "SCENARIOS.md", "ARCHITECTURE.md",
        "AGENTS.md", "CODEGUIDE.md", "ART.md", "CONTEXT.md",
        "SNIFFTEST.md", "README.md",
    ]

    for fname in template_files:
        src = templates_dir / fname
        dest = project_root / fname
        if src.exists():
            results[fname] = copy_if_missing(src, dest, replacements)
        else:
            results[fname] = "error: template not found"

    # Create .claude/ directory
    claude_dir = project_root / ".claude"
    if not claude_dir.exists():
        claude_dir.mkdir(parents=True, exist_ok=True)
        results[".claude/"] = "created"
    else:
        results[".claude/"] = "skipped"

    return results


def scaffold_comprehension(project_root: Path) -> dict:
    """Set up CodeGlass comprehension layer.

    Returns dict of {path: status}.
    """
    bs_root = get_brainstormer_root()
    results = {}

    # Create docs/codeglass/ directory
    codeglass_dir = project_root / "docs" / "codeglass"
    if not codeglass_dir.exists():
        codeglass_dir.mkdir(parents=True, exist_ok=True)
        results["docs/codeglass/"] = "created"
    else:
        results["docs/codeglass/"] = "skipped"

    # Copy rules.md template
    rules_src = bs_root / "comprehension" / "templates" / "rules.md"
    rules_dest = project_root / "rules.md"
    results["rules.md"] = copy_if_missing(rules_src, rules_dest)

    # Copy eval script
    eval_src = bs_root / "comprehension" / "scripts" / "eval.sh"
    eval_dest = project_root / "scripts" / "eval.sh"
    results["scripts/eval.sh"] = copy_if_missing(eval_src, eval_dest)

    return results


def scaffold_ideation(project_root: Path) -> dict:
    """Set up BrainStormer ideation layer.

    Returns dict of {path: status}.
    """
    bs_root = get_brainstormer_root()
    results = {}

    # Create brainstormer/ directory
    ideation_dir = project_root / "brainstormer"
    if not ideation_dir.exists():
        ideation_dir.mkdir(parents=True, exist_ok=True)
        results["brainstormer/"] = "created"
    else:
        results["brainstormer/"] = "skipped"

    # Copy ruleset template
    ruleset_src = bs_root / "ideation" / "ruleset-template.md"
    ruleset_dest = project_root / "brainstormer" / "ruleset.md"
    results["brainstormer/ruleset.md"] = copy_if_missing(ruleset_src, ruleset_dest)

    # Create empty output files
    for fname in ["angles.md", "hooks.md", "calendar.md", "outlines.md"]:
        fpath = ideation_dir / fname
        if not fpath.exists():
            fpath.write_text(f"# BrainStormer: {fname.replace('.md', '').title()}\n\n"
                           f"<!-- Generated by BrainStormer init -->\n",
                           encoding="utf-8")
            results[f"brainstormer/{fname}"] = "created"
        else:
            results[f"brainstormer/{fname}"] = "skipped"

    return results


def scaffold_quality(project_root: Path) -> dict:
    """Set up PALADIN quality layer.

    Returns dict of {path: status}.
    """
    bs_root = get_brainstormer_root()
    results = {}

    # Copy paladin config
    config_src = bs_root / "quality" / "templates" / "paladin-config-default.json"
    config_dest = project_root / "paladin.config.json"
    results["paladin.config.json"] = copy_if_missing(config_src, config_dest)

    return results


def write_version_marker(project_root: Path):
    """Write .brainstormer-version file to mark this project as initialized."""
    marker = project_root / ".brainstormer-version"
    marker.write_text(
        f"version: 1.0.0\n"
        f"initialized: {datetime.now().isoformat()}\n"
        f"skills: kernel,comprehension,ideation,quality\n",
        encoding="utf-8"
    )
